document.write('<style>'
+'.clearfix{display:block}'
+'.clearfix:after{content:".";display:block;height:0;visibility:hidden;clear:both}'
+'.clearfix{zoom:1}'
+'#footer{ width:980px; margin:0 auto; padding:35px 0;}'
+'#footer .copy-info{ float:left; width:520px; color:#959595; font-family:simsun;}'
+'#footer .copy-info span{ font-family:Arial; font-size:9px;}'
+'#footer .copy-info p{ line-height:1.4em;}'
+'#footer .copy-standard{ float:right; width:276px; height:52px; position:relative; background:url(https://img2.tiancitycdn.com/portal/servicesys/images/footer.jpg) no-repeat scroll 0 0; color:#FFF;}'
+'#footer .copy-standard a.zx110{ position:absolute; left:43px; top:0; width:40px; height:52px; text-indent:-999em; overflow:hidden;}'
+'#footer .copy-standard p{ position:absolute; left:105px; top:3px; width:170px;}'
+'#footer .copy-standard p *{ float:left;}'
+'#footer .copy-standard a{ width:52px; height:14px; color:#FFF; font-family:simhei; font-size:11px;}'
+'#footer .copy-standard span{ width:105px; height:14px; padding:0 0 0 13px; font-size:11px; font-family:simsun;}'
+'</style>'
+'<div id="footer" class="clearfix">'
+'<div class="copy-info">'
+'<p>网络实名：世纪天成 | 上海邮通科技有限公司 版权所有 | 24小时客户热线：021-34144567<br>上海市徐汇区钦州北路1066号74号楼3楼. 邮编：200233 <br><span>Copyright &copy; 2017 Shanghai Posts &amp; Telecommunications Technology CO.,LTD.</span></p>'
+'</div>'
+'<div class="copy-standard">'
+'<a class="zx110" href="http://www.zx110.org/" target="_blank" title="网络社会征信网">网络社会征信网</a>'
+'<p class="clearfix"><a href="#" target="_blank" title="沪网文">沪网文</a><span>[2016]0095-095</span><a href="#" target="_blank" title="沪ICP证">沪ICP证</a><span>B2-20040070</span><a href="#" target="_blank" title="(沪)字017号">新出网证</a><span>(沪)字017号</span></p>'
+'</div>'
+'</div>');